[sna-lgtc-boot] Fix indentation

diff --git a/sna-lgtc-boot/sna-lgtc-boot b/sna-lgtc-boot/sna-lgtc-boot
--- a/sna-lgtc-boot/sna-lgtc-boot
+++ b/sna-lgtc-boot/sna-lgtc-boot
@@ -18,24 +18,24 @@ if [ -f "$LGTC_FLASH_FILE" ] ; then
     
     # format SD card and add it to /etc/fstab
     if [ ! -e "$MMC" ]; then
-      echo "SD card not found!" 1>&2
-      exit 1
+        echo "SD card not found!" 1>&2
+        exit 1
     fi
 
     echo -e "o\nn\np\n1\n\n\nw" | fdisk "$MMC"
 
     if [ $? -ne 0 ]; then
-      exit 1
+        exit 1
     else
-      mkfs.ext4 -F "$MMC"p1
+        mkfs.ext4 -F "$MMC"p1
     fi
 
     mkdir -p /media/sdcard
 
     mount "$MMC"p1 /media/sdcard/
     if [ $? -ne 0 ]; then
-      rmdir /media/sdcard
-      exit 1
+        rmdir /media/sdcard
+        exit 1
     fi
 
     echo "$MMC""p1    /media/sdcard    ext4    defaults,nofail    0    0" >> /etc/fstab
